pi-cross-compile:       
  image: wpilib/raspbian-cross-ubuntu:10-18.04
  script:
    - cmake -B build-pi -DIS_CROSS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=CMake/arm-pi-gnueabihf.toolchain.cmake
    - cmake --build build-pi --target ecs_pi -- -j 8
  artifacts:
    paths:
      - build-pi/src/ecs_pi

sim-windows:       
  tags:
    - windows
  before_script:
    - choco install -y cmake
    - $env:Path += ';C:\Program Files\CMake\bin'
  script:
    - cmake -B build-sim
    - cmake --build build-sim --target ecs_sim
  artifacts:
    paths:
      - build-sim/Debug/ecs_sim.exe
  rules: # Currently only running windows builds on MRs to reduce build time
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

sim-linux:       
  image: gcc
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
  script:
    - cmake -B build-sim
    - cmake --build build-sim --target ecs_sim
  artifacts:
    paths:
      - build-sim/ecs_sim

