//
// Created by kevin on 5/27/2022.
//

#include "utils-and-constants/HorizontalECSRedlines.h"



extern const std::vector<const IRedline*> ONLINE_SAFE_D = {
        //REMOTELY CONTROLLED VALVES
        new ValveRedline("loxVent",
                         [](const SensorData *data) { return data->loxVent; },
                         OPEN),
        new ValveRedline("kerVent",
                         [](const SensorData *data) { return data->kerVent; },
                         OPEN),
        new ValveRedline("loxDrip",
                         [](const SensorData *data) { return data->loxDrip; },
                         OPEN),
        new ValveRedline("kerDrip",
                         [](const SensorData *data) { return data->kerDrip; },
                         OPEN),
        new ValveRedline("loxPressurant",
                         [](const SensorData *data) { return data->loxPressurant; },
                         CLOSED),
        new ValveRedline("kerPressurant",
                         [](const SensorData *data) { return data->kerPressurant; },
                         CLOSED),
        new ValveRedline("loxFlow",
                         [](const SensorData *data) { return data->loxFlow; },
                         CLOSED),
        new ValveRedline("kerFlow",
                         [](const SensorData *data) { return data->kerFlow; },
                         CLOSED),
        new ValveRedline("loxPurge",
                         [](const SensorData *data) { return data->loxPurge; },
                         CLOSED),
        new ValveRedline("kerPurge",
                         [](const SensorData *data) { return data->kerPurge; },
                         CLOSED),
        //PRESSURE SENSORS (psi)
        new IntWithinRedline("loxTankDucer",
                             [](const SensorData *data) { return data->loxTankDucer; },
                             0, 15),
        new IntWithinRedline("kerTankDucer",
                             [](const SensorData *data) { return data->kerTankDucer; },
                             0, 15),
        new IntWithinRedline("purgeDucer",
                             [](const SensorData *data) { return data->purgeDucer; },
                             0, 500),
        new IntWithinRedline("loxInletDucer",
                             [](const SensorData *data) { return data->loxInletDucer; },
                             0, 15),
        new IntWithinRedline("manifoldInletDucer",
                             [](const SensorData *data) { return data->manifoldInletDucer; },
                             0, 15),
        new IntWithinRedline("kerInletDucer",
                             [](const SensorData *data) { return data->kerInletDucer; },
                             0, 15),
        new IntWithinRedline("loxVenturi",
                             [](const SensorData *data) { return data->loxVenturi; },
                             0, 15),
        new IntWithinRedline("kerVenturi",
                             [](const SensorData *data) { return data->kerVenturi; },
                             0, 15),
        //LOADCELL (lbf)
        new IntWithinRedline("loadcell",
                             [](const SensorData *data) { return data->loadCell; },
                             0, 15),
        //TEMP SENSORS (C)
        new IntWithinRedline("loxTank1",
                             [](const SensorData *data) { return data->loxTank1; },
                             20, 30),
        new IntWithinRedline("loxTank2",
                             [](const SensorData *data) { return data->loxTank2; },
                             20, 30),
        new IntWithinRedline("loxTank3",
                             [](const SensorData *data) { return data->loxTank3; },
                             20, 30),
        new IntWithinRedline("loxDripLine",
                             [](const SensorData *data) { return data->loxDripLine; },
                             20, 30),
        new IntWithinRedline("outsideThroat",
                             [](const SensorData *data) { return data->outsideThroat; },
                             20, 30),
        new IntWithinRedline("nozzle",
                             [](const SensorData *data) { return data->nozzle; },
                             20, 30),
        new IntWithinRedline("bhioewihfdsa",
                             [](const SensorData *data) { return data->nozzle; },
                             20, 400, ABORT)
};
