//
// Created by kevin on 2/23/2022.
//

#ifndef BETTER_ENGINE_CONTROL_SOFTWARE_COMMANDDATA_H
#define BETTER_ENGINE_CONTROL_SOFTWARE_COMMANDDATA_H

#endif //BETTER_ENGINE_CONTROL_SOFTWARE_COMMANDDATA_H

void foo() {

}
