#ifndef BETTER_ENGINE_CONTROL_SOFTWARE_ECSSTATE_H
#define BETTER_ENGINE_CONTROL_SOFTWARE_ECSSTATE_H

#include <string>
#include <map>

enum ECSState {
    FILL,
    READY_TO_PRESSURIZE,
    PRESSURIZING,
    FLOW,
    FIRE,
    PURGE_POST_FIRE,
    SAFE_POST_FIRE,
    UNKNOWN,
    // ----- STATES FOR LN2 FILL -----
    LOX_ALL_OPEN,
    LOX_FILL_VENTx2,
    LOX_FILL_VENTx1,
    LOX_ALL_CLOSED,
    LOX_FLOW_PRESSURIZED,
    LOX_FLOW_UNPRESSURIZED,
    LOX_ALL_VENTS,
    // ----- STATES FOR COLDFLOW -----
    ONLINE_SAFE,
    KER_FILL,
    KER_POST_FILL,
    LOX_FILL,
    LOX_POST_FILL,
    LOX_READY_TO_PRESSURIZE,
    LOX_PRESSURIZING,
    LOX_FLOW,
    KER_READY_TO_PRESSURIZE,
    KER_PRESSURIZING,
    KER_FLOW,
    LOX_ENGINE_PURGE,
    KER_ENGINE_PURGE,
    ALL_ENGINE_PURGE,
    LOX_TANK_PURGE,
    KER_TANK_PURGE,
    ALL_TANK_PURGE,
    ALL_READY_TO_PRESSURIZE,
    ALL_PRESSURIZING,
    ALL_FLOW
};

std::map<ECSState, std::string> ECSStateToStringMap = {
        {FILL, "FILL"},
        {READY_TO_PRESSURIZE, "READY_TO_PRESSURIZE"},
        {PRESSURIZING, "PRESSURIZING"},
        {FLOW, "FLOW"},
        {FIRE, "FIRE"},
        {PURGE_POST_FIRE, "PURGE_POST_FIRE"},
        {SAFE_POST_FIRE, "SAFE_POST_FIRE"},
        {UNKNOWN, "UNKNOWN"},
        // ----- STATES FOR LN2 FILL -----
        {LOX_ALL_OPEN, "LOX_ALL_OPEN"},
        {LOX_FILL_VENTx2, "LOX_FILL_VENTx2"},
        {LOX_FILL_VENTx1, "LOX_FILL_VENTx1"},
        {LOX_ALL_CLOSED, "LOX_ALL_CLOSED"},
        {LOX_FLOW_PRESSURIZED, "LOX_FLOW_PRESSURIZED"},
        {LOX_FLOW_UNPRESSURIZED, "LOX_FLOW_UNPRESSURIZED"},
        {LOX_ALL_VENTS, "LOX_ALL_VENTS"},
        // ----- STATES FOR COLDFLOW -----
        {ONLINE_SAFE, "ONLINE_SAFE"},
        {KER_FILL, "KER_FILL"},
        {KER_POST_FILL, "KER_POST_FILL"},
        {LOX_FILL, "LOX_FILL"},
        {LOX_POST_FILL, "LOX_POST_FILL"},
        {LOX_READY_TO_PRESSURIZE, "LOX_READY_TO_PRESSURIZE"},
        {LOX_PRESSURIZING, "LOX_PRESSURIZING"},
        {LOX_FLOW, "LOX_FLOW"},
        {KER_READY_TO_PRESSURIZE, "KER_READY_TO_PRESSURIZE"},
        {KER_PRESSURIZING, "KER_PRESSURIZING"},
        {KER_FLOW, "KER_FLOW"},
        {LOX_ENGINE_PURGE, "LOX_ENGINE_PURGE"},
        {KER_ENGINE_PURGE, "KER_ENGINE_PURGE"},
        {ALL_ENGINE_PURGE, "ALL_ENGINE_PURGE"},
        {LOX_TANK_PURGE, "LOX_TANK_PURGE"},
        {KER_TANK_PURGE, "KER_TANK_PURGE"},
        {ALL_TANK_PURGE, "ALL_TANK_PURGE"},
        {ALL_READY_TO_PRESSURIZE, "ALL_READY_TO_PRESSURIZE"},
        {ALL_PRESSURIZING, "ALL_PRESSURIZING"},
        {ALL_FLOW, "ALL_FLOW"}
};

std::map<std::string, ECSState> stringToECSStateMap = {
        {"ONLINE_SAFE", ONLINE_SAFE},
        {"FILL", FILL},
        {"READY_TO_PRESSURIZE", READY_TO_PRESSURIZE},
        {"PRESSURIZING", PRESSURIZING},
        {"FLOW", FLOW},
        {"FIRE", FIRE},
        {"PURGE_POST_FIRE", PURGE_POST_FIRE},
        {"SAFE_POST_FIRE", SAFE_POST_FIRE},
        {"UNKNOWN", UNKNOWN},
        // ----- STATES FOR LN2 FILL -----
        {"LOX_ALL_OPEN", LOX_ALL_OPEN},
        {"LOX_FILL_VENTx2", LOX_FILL_VENTx2},
        {"LOX_FILL_VENTx1", LOX_FILL_VENTx1},
        {"LOX_ALL_CLOSED", LOX_ALL_CLOSED},
        {"LOX_FLOW_PRESSURIZED", LOX_FLOW_PRESSURIZED},
        {"LOX_FLOW_UNPRESSURIZED", LOX_FLOW_UNPRESSURIZED},
        {"LOX_ALL_VENTS", LOX_ALL_VENTS},
        // ----- STATES FOR COLDFLOW -----
        {"KER_FILL", KER_FILL},
        {"KER_POST_FILL", KER_POST_FILL},
        {"LOX_FILL", LOX_FILL},
        {"LOX_POST_FILL", LOX_POST_FILL},
        {"LOX_READY_TO_PRESSURIZE", LOX_READY_TO_PRESSURIZE},
        {"LOX_PRESSURIZING", LOX_PRESSURIZING},
        {"LOX_FLOW", LOX_FLOW},
        {"KER_READY_TO_PRESSURIZE", KER_READY_TO_PRESSURIZE},
        {"KER_PRESSURIZING", KER_PRESSURIZING},
        {"KER_FLOW", KER_FLOW},
        {"LOX_ENGINE_PURGE", LOX_ENGINE_PURGE},
        {"KER_ENGINE_PURGE", KER_ENGINE_PURGE},
        {"ALL_ENGINE_PURGE", ALL_ENGINE_PURGE},
        {"LOX_TANK_PURGE", LOX_TANK_PURGE},
        {"KER_TANK_PURGE", KER_TANK_PURGE},
        {"ALL_TANK_PURGE", ALL_TANK_PURGE},
        {"ALL_READY_TO_PRESSURIZE", ALL_READY_TO_PRESSURIZE},
        {"ALL_PRESSURIZING", ALL_PRESSURIZING},
        {"ALL_FLOW", ALL_FLOW}
};

#endif //BETTER_ENGINE_CONTROL_SOFTWARE_ECSSTATE_H
