#ifndef BETTER_ENGINE_CONTROL_SOFTWARE_ECSSTATE_H
#define BETTER_ENGINE_CONTROL_SOFTWARE_ECSSTATE_H

enum ECSState {
    ONLINE_SAFE,
    FILL,
    READY_TO_PRESSURIZE,
    PRESSURIZING,
    FLOW,
    FIRE,
    PURGE_POST_FIRE,
    SAFE_POST_FIRE,
    UNKNOWN,
    // ----- STATES FOR LN2 FILL -----
    LOX_ALL_OPEN,
    LOX_FILL_VENTx2,
    LOX_FILL_VENTx1,
    LOX_ALL_CLOSED,
    LOX_FLOW_PRESSURIZED,
    LOX_FLOW_UNPRESSURIZED,
    LOX_ALL_VENTS,
    // ----- STATES FOR COLDFLOW -----
    KER_FILL,
    KER_POST_FILL,
    LOX_FILL,
    LOX_POST_FILL,
    LOX_READY_TO_PRESSURIZE,
    LOX_PRESSURIZING,
    LOX_FLOW,
    KER_READY_TO_PRESSURIZE,
    KER_PRESSURIZING,
    KER_FLOW,
    LOX_PURGE,
    KER_PURGE,
    LOX_FULL_PURGE,
    KER_FULL_PURGE
};

#endif //BETTER_ENGINE_CONTROL_SOFTWARE_ECSSTATE_H
