//
// Created by kevin on 4/13/2022.
//

#ifndef BETTER_ENGINE_CONTROL_SOFTWARE_ECSUTILS_H
#define BETTER_ENGINE_CONTROL_SOFTWARE_ECSUTILS_H

enum ECSValveState {
    OPEN,
    CLOSED,
    INVALID
};

#endif //BETTER_ENGINE_CONTROL_SOFTWARE_ECSUTILS_H
