//
// Created by kevin on 2/23/2022.
//

#ifndef BETTER_ENGINE_CONTROL_SOFTWARE_SENSORDATA_H
#define BETTER_ENGINE_CONTROL_SOFTWARE_SENSORDATA_H

#endif //BETTER_ENGINE_CONTROL_SOFTWARE_SENSORDATA_H

class SensorData{
    //TODO
};