//
// Created by kevin on 6/15/2022.
//

#ifndef BETTER_ENGINE_CONTROL_SOFTWARE_HORIZONTALECSSTATES_H
#define BETTER_ENGINE_CONTROL_SOFTWARE_HORIZONTALECSSTATES_H

#include "ECSState.h"

extern const ECSState ONLINE_SAFE_D;
#endif //BETTER_ENGINE_CONTROL_SOFTWARE_HORIZONTALECSSTATES_H
